spring:
  datasource:
    url: jdbc:mysql://132.232.36.151:3306/time?characterEncoding=utf8&useSSL=true
    username: time
    password: time
    name: time
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-wait-millis: 200
      max-total: 5
  application:
    name: time

mybatis:
  config-location: classpath:mybatis.xml  #mybatis配置文件路径
  type-aliases-package: com.hercats.dev.commonbase.model
  mapper-locations:
  - classpath:mapper/*.xml

server:
  port: 8080
  ssl:
    key-store: classpath:mevur.bennkyou.top.jks
    key-store-password: 3bkd8q2clgfvqm
    key-password: 3bkd8q2clgfvqm

logging:
  level:
    root: info
